if(NOT WIN32)
  string(ASCII 27 Escape)
  set(ColourReset "${Escape}[m")
  set(ColourBold  "${Escape}[1m")
  set(Red         "${Escape}[31m")
  set(Green       "${Escape}[32m")
  set(Yellow      "${Escape}[33m")
  set(Blue        "${Escape}[34m")
  set(Magenta     "${Escape}[35m")
  set(Cyan        "${Escape}[36m")
  set(White       "${Escape}[37m")
  set(BoldRed     "${Escape}[1;31m")
  set(BoldGreen   "${Escape}[1;32m")
  set(BoldYellow  "${Escape}[1;33m")
  set(BoldBlue    "${Escape}[1;34m")
  set(BoldMagenta "${Escape}[1;35m")
  set(BoldCyan    "${Escape}[1;36m")
  set(BoldWhite   "${Escape}[1;37m")
  unset(Escape)
endif()
